language: php
php:
  - 5.4
  - 5.5
env:
  - MAGE=1.9.0.1
  - MAGE=1.8.1.0
  - MAGE=1.7.0.2
before_script:
  - MAGE_DIR=build
  # Change composer Magento version
  - > 
    sed "s/\"1.9.0.1\"/\"$MAGE\"/g" < composer.json > composer.json.tmp
  - rm composer.json && mv composer.json.tmp composer.json
  # Installing dependencies
  - composer install
  # Installing magento version with prepared DB dump
  - bin/mage-ci install $MAGE_DIR $MAGE magento -c -n
  # Installing EcomDev_PHPUnit module
  - bin/mage-ci install-module $MAGE_DIR $(pwd)
  # Configuring EcomDev_PHPUnit module
  - bin/mage-ci shell $MAGE_DIR ecomdev-phpunit.php -a magento-config --db-name magento --same-db 1 --base-url http://test.magento.com/
  # Configuring test suite
  - bin/mage-ci shell $MAGE_DIR ecomdev-phpunit.php -a change-status
script:
  # output php ini info for checking the problem
  - bin/phpunit $MAGE_DIR --colors